### ISSUE TITLE
OpenEnrollment at Course  Creation.

### ISSUE THREAD

**Issue by oglave1** [todaycodemaster/Quality-circle-s-LMS#27]
Make sure that @course creation when you select "open Enrollment on the Academy Publish Course Page it is saying Open Enrollment.

**Comment by todaycodemaster** [comment]
![image](https://user-images.githubusercontent.com/80197242/159824787-dba6a05b-7d21-4df3-936a-c1afb9fbebbb.png)

Fixed the open and closed enrollment course
