### ISSUE TITLE
Blast out Email.

### ISSUE THREAD

**Issue by oglave1** [todaycodemaster/Quality-circle-s-LMS#29]
<img width="365" alt="Screen Shot 2022-03-24 at 7 00 03 AM" src="https://user-images.githubusercontent.com/64755464/159911914-5f3bbebf-e482-46fd-bb5f-510c2f9549a3.png">

Create dynamic email to blast out course creation just like it is published on the academy. 
[BlastOutMaildocx.pdf](https://github.com/todaycodemaster/Quality-circle-s-LMS/files/8341281/BlastOutMaildocx.pdf)

When it goes to the email they should be able to view or enroll and it takes them to the academy page.

**Comment by todaycodemaster** [comment]
fixed
