### ISSUE TITLE
Updated Blast out Mail Template

### ISSUE THREAD

**Issue by oglave1** [todaycodemaster/Quality-circle-s-LMS#31]
[EmailTemplate.pdf](https://github.com/todaycodemaster/Quality-circle-s-LMS/files/8359037/EmailTemplate.pdf)
![Quality Logo](https://user-images.githubusercontent.com/64755464/160305744-af627708-7a71-4fb5-aca5-0585ef9b8c3a.png)  (Update)
![recognised-training-provider-rtp](https://user-images.githubusercontent.com/64755464/160305747-389d6f0e-4828-4265-aafc-d47de030e88f.png)
[EmailTemplate.pdf](https://github.com/todaycodemaster/Quality-circle-s-LMS/files/8358703/EmailTemplate.pdf)
[EmailTemplate.docx](https://github.com/todaycodemaster/Quality-circle-s-LMS/files/8358642/EmailTemplate.docx)
[EmailTemplate.pdf](https://github.com/todaycodemaster/Quality-circle-s-LMS/files/8358643/EmailTemplate.pdf)

I am going to provide you with the logo of the company and of exemplar global which needs to be added to the mail as well. 
I have added logo to show you where to place it.

**Comment by todaycodemaster** [comment]
fixed
