### ISSUE TITLE
ABOUT 

### ISSUE THREAD

**Issue by oglave1** [todaycodemaster/Quality-circle-s-LMS#33]
ABOUT US PAGE ON THE LMS AND ACADEMY IS DEFAULTING TO THE SIGNUP PAGE INTEAD THE SITE. 
<img width="1325" alt="Screen Shot 2022-03-28 at 11 46 19 AM" src="https://user-images.githubusercontent.com/64755464/160447539-8b075ce1-2b4f-4c92-a7bf-22199bf2147b.png">

CAN YOU FIX THIS?

**Comment by todaycodemaster** [comment]
![image](https://user-images.githubusercontent.com/80197242/160449206-5ec689cc-5237-429c-8742-463f7ed39244.png)
fixed
